#!/bin/bash

echo "::: running test..."

hwaf=`pwd`/waf
DESTDIR=`pwd`/install-area
OUTDIR=`pwd`/__build__
HWAF_OS=`uname | tr 'A-Z' 'a-z'`

/bin/rm -rf install-area proj-b-*.tar.gz __build__

echo "::::::::::::::::::::::"
echo "::: building proj-a..."
pushd proj-a || exit 1
/bin/rm -rf install-area proj-a-*.tar.gz __build__

$hwaf configure \
    --prefix=/opt/sw/mana/proj-a \
    --destdir=${DESTDIR} \
    --out=${OUTDIR} \
    build install \
    bdist \
    || exit 1

tar ztvf proj-a-x86_64-${HWAF_OS}-gcc-opt-0.0.1.tar.gz || exit 1

popd || exit 1

echo ""
echo "::::::::::::::::::::::"
echo "::: building proj-b..."
pushd proj-b || exit 1
/bin/rm -rf install-area proj-b-*.tar.gz __build__

$hwaf configure \
    --prefix=/opt/sw/mana/proj-b \
    --destdir=${DESTDIR} \
    --out=${OUTDIR} \
    --projects=/opt/sw/mana/proj-a:/not/there \
    build install \
    bdist \
    || exit 1

tar ztvf proj-b-x86_64-${HWAF_OS}-gcc-opt-0.0.1.tar.gz || exit 1

popd || exit 1


echo ""
echo "::::::::::::::::::::::"
echo "::: building proj-c..."
pushd proj-c || exit 1
/bin/rm -rf install-area proj-c-*.tar.gz __build__

$hwaf configure \
    --prefix=/opt/sw/mana/proj-c \
    --destdir=${DESTDIR} \
    --out=${OUTDIR} \
    --projects=/opt/sw/mana/proj-b \
    build install \
    bdist \
    || exit 1

tar ztvf proj-c-x86_64-${HWAF_OS}-gcc-opt-0.0.1.tar.gz || exit 1

popd || exit 1

echo ":::::::::::::::::::::::::::"
echo "::: testing user-install..."
/bin/rm -rf usr-install
/bin/mkdir usr-install || exit 1
tarfiles=`/bin/ls ${PWD}/proj-?/proj-*-0.0.1.tar.gz`
pushd usr-install || exit 1
for tarfile in $tarfiles; do
	echo "::: untarring [$(basename $tarfile)]..."
	tar -zxf $tarfile || exit 1
done
popd || exit 1

/bin/rm -rf usr-test
hwaf init usr-test || exit 1
pushd usr-test || exit 1

hwaf setup -project=../usr-install/opt/sw/mana/proj-c . || exit 1
../waf configure || exit 1
../waf show-projects || exit 1
popd usr-test || exit 1
