# -*- python -*-

import waflib.Logs as msg

def pkg_deps(ctx):
    # FIXME: cross-project use_pkg does not work yet!
    #ctx.use_pkg('rootcomps')
    return

def configure(ctx):


    if not ctx.env.HEPWAF_FOUND_ROOT:
        ctx.fatal("load a ROOT environment first!")
        pass
    
    ctx.start_msg("ROOT-CONFIG")
    ctx.end_msg(ctx.env['ROOT-CONFIG'])

    return

def build(ctx):

    if not ctx.env.PYTHON:
        ctx.fatal("load a python environment first!")
        pass

    if not ctx.env.HEPWAF_FOUND_ROOT:
        ctx.fatal("load a ROOT environment first!")
        pass
    
    if not ctx.env.HEPWAF_FOUND_LIBXML2:
        ctx.fatal("load a libxml2 environment first!")
        pass
    
    ctx(
        features="cxx cxxshlib",
        name="proj-b-rootcomps",
        source="src/th1d.cxx",
        target="projb-rootcomps",
        use="ROOT rootcomps",
        )

    pybin = ctx.env['PYTHON']
    if isinstance(pybin, list):
        pybin = pybin[0]
        pass
    ctx.symlink_as('${INSTALL_AREA}/bin/my-python', pybin)

    return

def install(ctx):
    return
