# -*- python -*-

def pkg_deps(ctx):
    return

def configure(ctx):
    return

def build(ctx):
    ctx(
        features="cxx cxxshlib",
        name="bfd-fpe",
        source="src/fpe.cxx",
        target="bfd-fpe",
        use="bfd",
        defines=['PACKAGE="posixcomps"',
                 'PACKAGE_VERSION="posixcomps-00-00-01"'],
        )
    return

def install(ctx):
    return
