# -*- python -*-

def pkg_deps(ctx):
    return

def configure(ctx):
    return

def build(ctx):
    ctx(
        features="cxx cxxprogram",
        name="tbb-hello",
        source="src/tbb-hello.cxx",
        target="tbb-hello",
        use="tbb",
        )
    return

def install(ctx):
    return
